### ISSUE TITLE
Unable to find the RinexData class 

### ISSUE THREAD

**Issue by srimant03** [luiscancillo/RINEXtools#1]
I wen through the codes RINEXtoCSV.cpp and RINEXtoRINEX.cpp but i couldn't find where is the RinexData class defined and implemented.

**Comment by luiscancillo** [comment]
You have to look inside the 'CommonClasses' project. It contains the classes common to all tools.

**Comment by luiscancillo** [comment]
Srimat,
You have to look inside the 'CommonClasses' project. It contains the classes common to all tools.
Best regards,


________________________________
De: Srimant Mohanty ***@***.***>
Enviado: miércoles, 26 de junio de 2024 13:20
Para: luiscancillo/RINEXtools ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [luiscancillo/RINEXtools] Unable to find the RinexData class (Issue #1)
